# Generated by Django 5.2.9 on 2025-12-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=50, null=True, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=50)),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
